2024-04-02 18:56:42,727 - INFO] DVC training
2024-04-02 18:56:42,727 - INFO] config :
2024-04-02 18:56:42,728 - INFO] {
    "tot_epoch": 10000,
    "tot_step": 2000000,
    "train_lambda": 1024,
    "lr": {
        "base": 0.0001,
        "decay": 0.1,
        "decay_interval": 1800000
    }
}
dataset find image:  323060
epoch 0
/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:3635: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:4004: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
Train epoch 0: [0/80765 (0.0%)]	Loss: 6190.786 |	MSE loss: 6.038 |	Bpp loss: 7.67 |	Aux loss: 0.00
Traceback (most recent call last):
  File "main_dvc.py", line 395, in <module>
    global_step = train(epoch, global_step)
  File "main_dvc.py", line 293, in train
    "train_batch/mse":mse_loss.avg,
AttributeError: 'Tensor' object has no attribute 'avg'